# Generated by Django 4.2.7 on 2023-11-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.CharField(max_length=200, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='short description'),
        ),
    ]
