# Generated by Django 5.0.4 on 2024-05-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_projectskill_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='detail',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
