# Generated by Django 5.0.4 on 2024-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skillcategory_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='detail_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='detail_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
