name: Docker Image CI

on:
  push:
    tags:
    - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          
      - uses: actions/checkout@v4
      - name: 'Build & Push image'
        run: |
          docker build . --tag ghcr.io/enzopb/portfolio:${{ github.ref_name }}
          docker push ghcr.io/enzopb/portfolio:${{ github.ref_name }}
