name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: 'Build & Push image'
        run: |
          docker build . --tag ghcr.io/EnzoPB/portfolio:${{ github.event.release.name }}
          docker push ghcr.io/EnzoPB/portfolio:${{ github.event.release.name }}
